# Generated by Django 4.0.5 on 2022-06-26 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='todayuser',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='todayuser',
            name='is_number',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('poster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.poster')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            bases=('apps.poster',),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('poster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.poster')),
                ('date', models.DateField()),
                ('price', models.PositiveIntegerField()),
            ],
            bases=('apps.poster',),
        ),
        migrations.AddField(
            model_name='poster',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.poster')),
            ],
        ),
    ]
