# Generated by Django 4.0.5 on 2022-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='poster',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='./media/postes'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
