# Generated by Django 4.0.5 on 2022-07-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_poster_owner_remove_poster_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
