# Generated by Django 4.0.5 on 2022-06-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_poster_rename_today_admin_todayuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayuser',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
