# Generated by Django 4.0.5 on 2022-06-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_todayuser_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayuser',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
