# Generated by Django 4.0.5 on 2022-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_todayuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='title',
            field=models.CharField(default='Trip', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(upload_to='./media/postes'),
        ),
        migrations.AlterField(
            model_name='todayuser',
            name='img',
            field=models.ImageField(blank=True, upload_to='./media'),
        ),
    ]
