# Generated by Django 4.0.5 on 2022-07-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
    ]
